[project]
name = "news-deframer-mining"
version = "0.1.0"
description = "News Deframer Trend Mining Modules"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4",
    "numpy>=2.4.4,<3.0",
    "psycopg2-binary",
    "pydantic-settings",
    "pyarrow",
    "python-dotenv",
    "publicsuffix2",
    "spacy>=3.8.14,<3.10.0"
]

[project.scripts]
miner-cli = "news_deframer.cli.miner:main"

[dependency-groups]
dev = [
    "ruff",
    "pytest",
    "mypy",
    "types-psycopg2",
]

[tool.pytest.ini_options]
pythonpath = [
    ".",
]

[build-system]
requires = ["setuptools>=82.0.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["news_deframer*"]
