"""Language-specific helpers for extracting Memolon sentiment scores."""

from __future__ import annotations

import logging
import time
from statistics import mean
from pathlib import Path
from typing import Any, Sequence, TypedDict, cast

from news_deframer.logger import _format_bytes, _get_rss_bytes
from news_deframer.memolon_models import MEMOLON_LANGUAGE_MODELS

try:  # pragma: no cover - optional dependency behavior
    import pyarrow.parquet as pq  # type: ignore[import-untyped]
except Exception:  # pragma: no cover - optional dependency behavior
    pq = None  # type: ignore[assignment]


_MEMOLON_CACHE: dict[str, tuple[Any, list[str]]] = {}


logger = logging.getLogger(__name__)

# Aggregation motivation:
# - Median is robust to outliers, but in NLP those "outliers" are often the
#   emotionally meaningful words we want to preserve.
# - Stop-words should be filtered before sentiment aggregation so neutral filler
#   terms do not wash out the signal; this pipeline does that upstream.
# - VAD dimensions (valence, arousal, dominance) describe overall mood, so mean
#   pooling is a better fit than median for combining multiple matched words.
# - BE5 dimensions (joy, anger, sadness, fear, disgust) describe discrete
#   emotional intensity, so max pooling better preserves strong spikes.
# - Average/mean is also a valid BE5 option when a smoother aggregate is more
#   useful than preserving the strongest emotional cue, but it will mute peaks.

_VAD_KEYS = frozenset({"v", "a", "d"})


class Sentiment(TypedDict, total=False):
    """Compact sentiment payload based on Memolon sentiment ratings.

    1. The Dimensional Approach (VAD) | Scale: 1.0 to 9.0 (5.0 is Neutral)
    - `v` (Valence): Polarity/Pleasantness
      (1 = max negative, 9 = max positive)
    - `a` (Arousal): Activation/Excitement
      (1 = sleepy/sluggish, 9 = excited/frantic)
    - `d` (Dominance): Perceived control
      (1 = submissive/weak, 9 = dominant/powerful)

    2. The Discrete Approach (BE5) | Scale: 1.0 to 5.0
       (1.0 is Neutral/Absence)
    - `j` (Joy)
    - `a_n` (Anger)
    - `s` (Sadness)
    - `f` (Fear)
    - `d_g` (Disgust)

    For BE5, 1 indicates a total absence of the emotion, and 5 indicates
    maximum intensity of the emotion.

    Note: Because these scores were generated by a regression-based neural
    network via cross-lingual distant supervision, floating-point numbers may
    occasionally dip slightly below 1.0 or slightly above the documented
    maximums.
    """

    v: float
    a: float
    d: float
    j: float
    a_n: float
    s: float
    f: float
    d_g: float


_SENTIMENT_COLUMN_MAP = {
    "valence": "v",
    "arousal": "a",
    "dominance": "d",
    "joy": "j",
    "anger": "a_n",
    "sadness": "s",
    "fear": "f",
    "disgust": "d_g",
}


def _set_sentiment_value(sentiment: Sentiment, column_name: str, value: Any) -> None:
    numeric_value = float(value)
    if column_name == "valence":
        sentiment["v"] = numeric_value
    elif column_name == "arousal":
        sentiment["a"] = numeric_value
    elif column_name == "dominance":
        sentiment["d"] = numeric_value
    elif column_name == "joy":
        sentiment["j"] = numeric_value
    elif column_name == "anger":
        sentiment["a_n"] = numeric_value
    elif column_name == "sadness":
        sentiment["s"] = numeric_value
    elif column_name == "fear":
        sentiment["f"] = numeric_value
    elif column_name == "disgust":
        sentiment["d_g"] = numeric_value


def _get_language_code(language: str) -> str:
    """Extract the base language code (e.g., 'en-US' -> 'en')."""
    return (language or "").split("-")[0].lower()


def _get_memolon_model(language: str) -> tuple[Any, list[str]]:
    """Load and cache the Memolon table and lowercase word index for a language."""
    if pq is None:
        raise RuntimeError("pyarrow is required but not installed")

    lang_code = _get_language_code(language)
    if not lang_code:
        raise RuntimeError("Language code is required for sentiment handling")

    cached = _MEMOLON_CACHE.get(lang_code)
    if cached is not None:
        return cached

    model_filename = MEMOLON_LANGUAGE_MODELS.get(lang_code)
    if not model_filename:
        raise RuntimeError(f"No Memolon model available for language '{language}'")

    model_path = Path(__file__).resolve().parent.parent / "memolon" / model_filename
    if not model_path.exists():
        raise RuntimeError(f"Memolon model file not found: {model_path}")

    started_at = time.perf_counter()
    rss_before = _get_rss_bytes()
    try:
        table = pq.read_table(model_path)
    except Exception as exc:  # pragma: no cover - propagate failure gracefully
        raise RuntimeError(f"Failed to load Memolon model '{model_filename}'") from exc

    read_elapsed = time.perf_counter() - started_at

    if "word" not in table.column_names:
        raise RuntimeError(f"Memolon model '{model_filename}' has no 'word' column")

    index_started_at = time.perf_counter()
    lowercase_word_list = [
        str(word).lower() for word in table.column("word").to_pylist()
    ]
    index_elapsed = time.perf_counter() - index_started_at
    total_elapsed = time.perf_counter() - started_at
    rss_after = _get_rss_bytes()
    rss_delta = (
        rss_after - rss_before
        if rss_before is not None and rss_after is not None
        else None
    )
    disk_size_bytes = model_path.stat().st_size
    table_nbytes = getattr(table, "nbytes", None)

    logger.info(
        "Loaded Memolon model '%s' in %.3fs (disk=%s, table=%s, rss_delta=%s, read=%.3fs, index=%.3fs)",
        model_filename,
        total_elapsed,
        _format_bytes(disk_size_bytes),
        _format_bytes(table_nbytes if isinstance(table_nbytes, int) else None),
        _format_bytes(rss_delta),
        read_elapsed,
        index_elapsed,
        extra={
            "language": language,
            "path": str(model_path),
            "disk_size": _format_bytes(disk_size_bytes),
            "table_size": _format_bytes(
                table_nbytes if isinstance(table_nbytes, int) else None
            ),
            "rss_delta": _format_bytes(rss_delta),
        },
    )

    cached_model = (table, lowercase_word_list)
    _MEMOLON_CACHE[lang_code] = cached_model
    return cached_model


def extract_sentiments(word_to_find: str, language: str) -> Sentiment | None:
    """Return compact Memolon sentiment scores for a single word.

    1. The Dimensional Approach (VAD) | Scale: 1.0 to 9.0 (5.0 is Neutral)
    - Valence: Polarity/Pleasantness (1 = max negative, 9 = max positive)
    - Arousal: Activation/Excitement (1 = sleepy/sluggish, 9 = excited/frantic)
    - Dominance: Perceived control (1 = submissive/weak, 9 = dominant/powerful)

    2. The Discrete Approach (BE5) | Scale: 1.0 to 5.0
       (1.0 is Neutral/Absence)
    - Joy
    - Anger
    - Sadness
    - Fear
    - Disgust

    For BE5, 1 indicates a total absence of the emotion, and 5 indicates
    maximum intensity of the emotion.

    Note: Because these scores were generated by a regression-based neural
    network via cross-lingual distant supervision, floating-point numbers may
    occasionally dip slightly below 1.0 or slightly above the documented
    maximums.
    """
    normalized = word_to_find.strip()
    if not normalized:
        return None

    table, lowercase_word_list = _get_memolon_model(language)
    lowercase_word_to_find = normalized.lower()

    try:
        index = lowercase_word_list.index(lowercase_word_to_find)
    except ValueError:
        return None

    sentiment: Sentiment = {}
    for column_name in _SENTIMENT_COLUMN_MAP:
        if column_name in table.column_names:
            value = table.column(column_name)[index].as_py()
            if value is not None:
                _set_sentiment_value(sentiment, column_name, value)

    return sentiment


def extract_sentiments_array(
    stems: tuple[Sequence[str], Sequence[str], Sequence[str]], language: str
) -> Sentiment | None:
    """Return aggregated sentiment scores across matched words.

    The input typically contains noun, verb, and adjective stems. Each word is
    looked up independently, missing words are ignored, VAD dimensions are
    averaged, and BE5 dimensions use max pooling. Mean/average is also a
    reasonable BE5 alternative when a smoother aggregate is preferred.
    """

    collected_values: dict[str, list[float]] = {
        key: [] for key in Sentiment.__annotations__
    }

    for words in stems:
        for word in words:
            sentiment = extract_sentiments(word, language)
            if sentiment is None:
                continue
            for key, value in sentiment.items():
                collected_values[key].append(cast(float, value))

    aggregated: Sentiment = {}
    for key, values in collected_values.items():
        if not values:
            continue

        aggregate_value = mean(values) if key in _VAD_KEYS else max(values)
        rounded_value = round(float(aggregate_value), 2)
        if key == "v":
            aggregated["v"] = rounded_value
        elif key == "a":
            aggregated["a"] = rounded_value
        elif key == "d":
            aggregated["d"] = rounded_value
        elif key == "j":
            aggregated["j"] = rounded_value
        elif key == "a_n":
            aggregated["a_n"] = rounded_value
        elif key == "s":
            aggregated["s"] = rounded_value
        elif key == "f":
            aggregated["f"] = rounded_value
        elif key == "d_g":
            aggregated["d_g"] = rounded_value

    return aggregated or None
